### ISSUE TITLE
Can't login with an error

### ISSUE THREAD

**Issue by neroti9n** [frysztak/orpington-news#94] opened 2022-11-28 14:11 UTC
hello, i get an error when i was logining
![image](https://user-images.githubusercontent.com/15121488/204298160-84ced464-167f-4e63-baca-284a9949498b.png)
![image](https://user-images.githubusercontent.com/15121488/204298008-b447573e-e574-49f8-b8dd-dd81b77ca4bc.png)

**Comment by neroti9n** [comment] 2022-11-28 16:07
Not yet...maybe this is the crux of the problem...so i can't use it through NOT HTTPS?

**Comment by frysztak** [comment] 2022-11-28 16:14
in general you should be able not to use HTTPS, but I missed the fact that [Cache API](https://developer.mozilla.org/en-US/docs/Web/API/Cache) is not available in non-secure contexts. I'll prepare patch release with a fix right now

**Comment by frysztak** [comment] 2022-11-28 17:26
@neroti9n this should be fixed in [v0.9.1](https://github.com/frysztak/orpington-news/releases/tag/0.9.1). please pull newest image and try logging in again

**Comment by neroti9n** [comment] 2022-11-29 01:12
thanks~

**Comment by neroti9n** [comment] 2022-11-29 01:30
i have updated to the newest image, it didn' t show last error, but api returned http errorcode 401 Unauthorized

**Comment by frysztak** [comment] 2022-11-29 08:17
I'll later setup env without HTTPS to debug this

**Comment by frysztak** [comment] 2022-11-29 15:52
@neroti9n can you try adding environmental variable `DISABLE_SECURE_COOKIE=true`? following sample [`docker-compose.template.yml`](https://github.com/frysztak/orpington-news/blob/master/docker-compose.template.yml):
```yaml
version: '3'
services:
  orpington-news:
    image: ghcr.io/frysztak/orpington-news-api:latest
    container_name: orpington-news
    environment:
      - APP_URL=https://news.my.domain # please change to your actual domain
      - DB_HOST=orpington-news-postgres
      - DB_PASS=dbpass # same pass like `POSTGRES_PASSWORD` below
      - COOKIE_SECRET=<generate unique cookie secret, for details see README>
      - DISABLE_SECURE_COOKIE=true
      # ^^ that's the line
    networks:
      - orpington-news
    restart: always

  orpington-news-postgres:
    image: postgres:14-alpine
    container_name: orpington-news-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=dbpass
    volumes:
      - <local directory>:/var/lib/postgresql/data
    networks:
      - orpington-news
    restart: always

networks:
  orpington-news:
```

**Comment by neroti9n** [comment] 2022-11-30 05:14
I logged in my account successfully, thank u very much~
^^there are some small tips to make it better
1、mark unread/read in different colors or signs to distinguish them
2、it could add a Favourits folder putting in some worth re-reading articals
3、it didn't display suitable size on my phone at first time, i swithed the layout, then seems to be normal, at the first time,it will display the scroll in the bottom that makes page move left and right

**Closed** 2022-11-30 05:15 UTC

**Comment by frysztak** [comment] 2022-11-30 07:19
glad it worked 🎊. sorry it took so much effort - I kind of assumed everyone will use HTTPS from the start. I'll try to add a note in readme about it

and thanks for the tips! some kind of Favourites folder is on my TODO list from the very beginning. I'm curious about the third one - can you share your phone model and browser?

**Comment by neroti9n** [comment] 2022-11-30 10:35
iphone12 & safari...other browsers seem like also have the same problem

I find another pagination problem, when I scroll down to the bottom in the collection list, the upper items will become the same and can't be recovered

**Comment by frysztak** [comment] 2022-11-30 18:24
> other browsers seem like also have the same problem
because of Apple policy all browsers on iOS use WebKit

truth be told, I haven't done any testing on iOS devices because I don't own any. but I'll try to line something up. many thanks for the feedback, I really appreciate it

**Comment by neroti9n** [comment] 2022-12-01 06:04
As a web developer, too, I don't even know the security policy different between https and http without google search, and browsers on ios all use Webkit...lol..learned~

What's the brand of your phone? Samsung or  Xiaomi or Sony or ...I'm just curious whether our country's brand have a good sale in your place^^

**Comment by frysztak** [comment] 2022-12-04 10:56
@neroti9n I use a Motorola.
I couldn't reproduce those iOS issues you mentioned - could you open a new bug report with screenshots/video?
